import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WalletConnect from '../Components/WalletConnect'
import { useWallet } from "@manahippo/aptos-wallet-adapter"
import Disperse from '../Components/Disprese'
const Home: NextPage = () => {
  const { wallet } = useWallet()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>
          verb distribute ether or tokens to multiple addresses
        </p>
        <WalletConnect />
      </div>

      <main className={styles.main}>
        <Disperse />
      </main>
    </div>
  )
}

export default Home
